site_name: Ambition-LiuKai's Blogs
site_url: https://github.com/Ambition-LiuKai/blogs
site_author: Ambition-LiuKai

nav:
  - Home: index.md
  - Blog:
    - "one": blog/index.md
    - "two": blog/posts/first.md
    - "three": blog/posts/second.md
  - tags: tags.md

# 系统预设主题颜色
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant  # 即时加载
    - navigation.instant.prefetch # 即时预取
    - navigation.instant.progress # 即时进度
    - navigation.tracking # 跟踪
    - navigation.tabs # 横向导航栏
    # - navigation.tabs.sticky # 粘性导航栏（固定在顶部）
    - navigation.sections # 目录(目录树)
    - navigation.expand # 目录(目录树)可展开
    - navigation.path # 路径导航
    # - navigation.prune # 目录(目录树)剪枝
    - navigation.indexes # 目录(目录树)索引
    - toc.follow # 目录(目录树)跟随
    - toc.integrate # 目录(目录树)集成
    - navigation.top # 返回顶部

    - search.suggest # 搜索建议
    - search.highlight # 搜索高亮
    - search.share # 搜索分享








  # 网站logo
  logo: assets/logo.png
  icon:
    logo: material/library
    tag: 
      foo: material/tag
      bar: material/tag-text
    # previous: fontawesome/solid/angle-left
    # next: fontawesome/solid/angle-right
  favicon: assets/logo.png

  # 主题字体
  font: 
    text: Roboto
    code: Roboto Mono

  # 主题色系
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 自动切换

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      toggle:
        icon: material/brightness-7
        name: 赞美太阳
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 赞美黑夜
    
extra_css:
  - css/extra.css
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css

extra_javascript:
  - js/shortcuts.js

extra:
  homepage: https://ambition-liukai.github.io/blogs/
  version:
    provider: mike
  generator: true
  tags:
    Foo: foo
    Bar: bar

plugins:
  - tags:
      tags_file: tags.md
  - search
  - blog:
      draft: true
      draft_on_serve: false
      draft_if_future_date: true
